services:
  postgres:
    image: postgres:16-alpine
    container_name: subscription-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: