server:
  port: 8080

spring:
  application:
    name: subscription-service

  datasource:
    url: jdbc:postgresql://localhost:5433/subscription_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    com.example.subscriptionservice: DEBUG
    org.springframework.web: DEBUG